M48
; DRILL file {KiCad 9.0.0} date 2025-10-19T17:53:06+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-10-19T17:53:06+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X191.11Y-145.82
X196.89Y-145.82
T2
X183.5Y-98.5
X183.5Y-147.5
X241.5Y-98.5
X241.5Y-147.5
M30
