M48
; DRILL file KiCad 10.0.3 date 2026-10-03T23:14:26
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-03T23:14:26+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X191.11Y-145.82
X196.89Y-145.82
T2
X183.5Y-98.5
X183.5Y-147.5
X241.5Y-98.5
X241.5Y-147.5
M30
